/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsAccountAliasesRouteImport } from './routes/docs/account-aliases'
import { Route as DocsApiReferenceRouteImport } from './routes/docs/api-reference'
import { Route as DocsArchitectureRouteImport } from './routes/docs/architecture'
import { Route as DocsBackendRouteImport } from './routes/docs/backend'
import { Route as DocsBlockStreamRouteImport } from './routes/docs/block-stream'
import { Route as DocsCompatibilityRouteImport } from './routes/docs/compatibility'
import { Route as DocsConfigurationRouteImport } from './routes/docs/configuration'
import { Route as DocsCustomJsonRouteImport } from './routes/docs/custom-json'
import { Route as DocsCustomJsonParserRouteImport } from './routes/docs/custom-json-parser'
import { Route as DocsEnginePaymentsRouteImport } from './routes/docs/engine-payments'
import { Route as DocsEnvironmentVariablesRouteImport } from './routes/docs/environment-variables'
import { Route as DocsErrorsRouteImport } from './routes/docs/errors'
import { Route as DocsHiveEngineRouteImport } from './routes/docs/hive-engine'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsKeychainRouteImport } from './routes/docs/keychain'
import { Route as DocsNativePaymentsRouteImport } from './routes/docs/native-payments'
import { Route as DocsNftIssuerRouteImport } from './routes/docs/nft-issuer'
import { Route as DocsPaymentStreamRouteImport } from './routes/docs/payment-stream'
import { Route as DocsPaymentValidationRouteImport } from './routes/docs/payment-validation'
import { Route as DocsPaymentsRouteImport } from './routes/docs/payments'
import { Route as DocsQuickStartRouteImport } from './routes/docs/quick-start'
import { Route as DocsRawCustomJsonRouteImport } from './routes/docs/raw-custom-json'
import { Route as DocsRawRpcRouteImport } from './routes/docs/raw-rpc'
import { Route as DocsReleaseNotesRouteImport } from './routes/docs/release-notes'
import { Route as DocsRpcResolutionRouteImport } from './routes/docs/rpc-resolution'
import { Route as DocsTokenIssuerRouteImport } from './routes/docs/token-issuer'
import { Route as DocsTransactionReaderRouteImport } from './routes/docs/transaction-reader'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs/troubleshooting'
import { Route as DocsTypesRouteImport } from './routes/docs/types'
import { Route as DocsUnifiedStreamRouteImport } from './routes/docs/unified-stream'
import { Route as DocsNftsBurnRouteImport } from './routes/docs/nfts/burn'
import { Route as DocsNftsCreateRouteImport } from './routes/docs/nfts/create'
import { Route as DocsNftsIssueRouteImport } from './routes/docs/nfts/issue'
import { Route as DocsNftsIssueMultipleRouteImport } from './routes/docs/nfts/issue-multiple'
import { Route as DocsNftsTransferRouteImport } from './routes/docs/nfts/transfer'
import { Route as DocsPlaygroundIndexRouteImport } from './routes/docs/playground/index'
import { Route as DocsPlaygroundConfigurationsRouteImport } from './routes/docs/playground/configurations'
import { Route as DocsPlaygroundCustomJsonRouteImport } from './routes/docs/playground/custom-json'
import { Route as DocsPlaygroundKeychainRouteImport } from './routes/docs/playground/keychain'
import { Route as DocsPlaygroundNodesRouteImport } from './routes/docs/playground/nodes'
import { Route as DocsPlaygroundPaymentMonitorRouteImport } from './routes/docs/playground/payment-monitor'
import { Route as DocsPlaygroundRawCustomJsonRouteImport } from './routes/docs/playground/raw-custom-json'
import { Route as DocsPlaygroundReaderRouteImport } from './routes/docs/playground/reader'
import { Route as DocsPlaygroundRpcRouteImport } from './routes/docs/playground/rpc'
import { Route as DocsPlaygroundUnifiedStreamRouteImport } from './routes/docs/playground/unified-stream'
import { Route as DocsTokensBurnRouteImport } from './routes/docs/tokens/burn'
import { Route as DocsTokensCreateRouteImport } from './routes/docs/tokens/create'
import { Route as DocsTokensIssueRouteImport } from './routes/docs/tokens/issue'
import { Route as DocsTokensTransferRouteImport } from './routes/docs/tokens/transfer'
import { Route as DocsPlaygroundNftBurnRouteImport } from './routes/docs/playground/nft/burn'
import { Route as DocsPlaygroundNftCreateRouteImport } from './routes/docs/playground/nft/create'
import { Route as DocsPlaygroundNftIssueRouteImport } from './routes/docs/playground/nft/issue'
import { Route as DocsPlaygroundNftIssueMultipleRouteImport } from './routes/docs/playground/nft/issue-multiple'
import { Route as DocsPlaygroundNftTransferRouteImport } from './routes/docs/playground/nft/transfer'
import { Route as DocsPlaygroundPaymentsEngineRouteImport } from './routes/docs/playground/payments/engine'
import { Route as DocsPlaygroundPaymentsNativeRouteImport } from './routes/docs/playground/payments/native'
import { Route as DocsPlaygroundTokenBurnRouteImport } from './routes/docs/playground/token/burn'
import { Route as DocsPlaygroundTokenCreateRouteImport } from './routes/docs/playground/token/create'
import { Route as DocsPlaygroundTokenIssueRouteImport } from './routes/docs/playground/token/issue'
import { Route as DocsPlaygroundTokenTransferRouteImport } from './routes/docs/playground/token/transfer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAccountAliasesRoute = DocsAccountAliasesRouteImport.update({
  id: '/account-aliases',
  path: '/account-aliases',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiReferenceRoute = DocsApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBackendRoute = DocsBackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBlockStreamRoute = DocsBlockStreamRouteImport.update({
  id: '/block-stream',
  path: '/block-stream',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCompatibilityRoute = DocsCompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCustomJsonRoute = DocsCustomJsonRouteImport.update({
  id: '/custom-json',
  path: '/custom-json',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCustomJsonParserRoute = DocsCustomJsonParserRouteImport.update({
  id: '/custom-json-parser',
  path: '/custom-json-parser',
  getParentRoute: () => DocsRoute,
} as any)
const DocsEnginePaymentsRoute = DocsEnginePaymentsRouteImport.update({
  id: '/engine-payments',
  path: '/engine-payments',
  getParentRoute: () => DocsRoute,
} as any)
const DocsEnvironmentVariablesRoute =
  DocsEnvironmentVariablesRouteImport.update({
    id: '/environment-variables',
    path: '/environment-variables',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsErrorsRoute = DocsErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHiveEngineRoute = DocsHiveEngineRouteImport.update({
  id: '/hive-engine',
  path: '/hive-engine',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsKeychainRoute = DocsKeychainRouteImport.update({
  id: '/keychain',
  path: '/keychain',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNativePaymentsRoute = DocsNativePaymentsRouteImport.update({
  id: '/native-payments',
  path: '/native-payments',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNftIssuerRoute = DocsNftIssuerRouteImport.update({
  id: '/nft-issuer',
  path: '/nft-issuer',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPaymentStreamRoute = DocsPaymentStreamRouteImport.update({
  id: '/payment-stream',
  path: '/payment-stream',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPaymentValidationRoute = DocsPaymentValidationRouteImport.update({
  id: '/payment-validation',
  path: '/payment-validation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPaymentsRoute = DocsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickStartRoute = DocsQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRawCustomJsonRoute = DocsRawCustomJsonRouteImport.update({
  id: '/raw-custom-json',
  path: '/raw-custom-json',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRawRpcRoute = DocsRawRpcRouteImport.update({
  id: '/raw-rpc',
  path: '/raw-rpc',
  getParentRoute: () => DocsRoute,
} as any)
const DocsReleaseNotesRoute = DocsReleaseNotesRouteImport.update({
  id: '/release-notes',
  path: '/release-notes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRpcResolutionRoute = DocsRpcResolutionRouteImport.update({
  id: '/rpc-resolution',
  path: '/rpc-resolution',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTokenIssuerRoute = DocsTokenIssuerRouteImport.update({
  id: '/token-issuer',
  path: '/token-issuer',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTransactionReaderRoute = DocsTransactionReaderRouteImport.update({
  id: '/transaction-reader',
  path: '/transaction-reader',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTypesRoute = DocsTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => DocsRoute,
} as any)
const DocsUnifiedStreamRoute = DocsUnifiedStreamRouteImport.update({
  id: '/unified-stream',
  path: '/unified-stream',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNftsBurnRoute = DocsNftsBurnRouteImport.update({
  id: '/nfts/burn',
  path: '/nfts/burn',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNftsCreateRoute = DocsNftsCreateRouteImport.update({
  id: '/nfts/create',
  path: '/nfts/create',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNftsIssueRoute = DocsNftsIssueRouteImport.update({
  id: '/nfts/issue',
  path: '/nfts/issue',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNftsIssueMultipleRoute = DocsNftsIssueMultipleRouteImport.update({
  id: '/nfts/issue-multiple',
  path: '/nfts/issue-multiple',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNftsTransferRoute = DocsNftsTransferRouteImport.update({
  id: '/nfts/transfer',
  path: '/nfts/transfer',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundIndexRoute = DocsPlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundConfigurationsRoute =
  DocsPlaygroundConfigurationsRouteImport.update({
    id: '/playground/configurations',
    path: '/playground/configurations',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPlaygroundCustomJsonRoute =
  DocsPlaygroundCustomJsonRouteImport.update({
    id: '/playground/custom-json',
    path: '/playground/custom-json',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPlaygroundKeychainRoute = DocsPlaygroundKeychainRouteImport.update({
  id: '/playground/keychain',
  path: '/playground/keychain',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundNodesRoute = DocsPlaygroundNodesRouteImport.update({
  id: '/playground/nodes',
  path: '/playground/nodes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundPaymentMonitorRoute =
  DocsPlaygroundPaymentMonitorRouteImport.update({
    id: '/playground/payment-monitor',
    path: '/playground/payment-monitor',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPlaygroundRawCustomJsonRoute =
  DocsPlaygroundRawCustomJsonRouteImport.update({
    id: '/playground/raw-custom-json',
    path: '/playground/raw-custom-json',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPlaygroundReaderRoute = DocsPlaygroundReaderRouteImport.update({
  id: '/playground/reader',
  path: '/playground/reader',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundRpcRoute = DocsPlaygroundRpcRouteImport.update({
  id: '/playground/rpc',
  path: '/playground/rpc',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundUnifiedStreamRoute =
  DocsPlaygroundUnifiedStreamRouteImport.update({
    id: '/playground/unified-stream',
    path: '/playground/unified-stream',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsTokensBurnRoute = DocsTokensBurnRouteImport.update({
  id: '/tokens/burn',
  path: '/tokens/burn',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTokensCreateRoute = DocsTokensCreateRouteImport.update({
  id: '/tokens/create',
  path: '/tokens/create',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTokensIssueRoute = DocsTokensIssueRouteImport.update({
  id: '/tokens/issue',
  path: '/tokens/issue',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTokensTransferRoute = DocsTokensTransferRouteImport.update({
  id: '/tokens/transfer',
  path: '/tokens/transfer',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundNftBurnRoute = DocsPlaygroundNftBurnRouteImport.update({
  id: '/playground/nft/burn',
  path: '/playground/nft/burn',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundNftCreateRoute = DocsPlaygroundNftCreateRouteImport.update({
  id: '/playground/nft/create',
  path: '/playground/nft/create',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundNftIssueRoute = DocsPlaygroundNftIssueRouteImport.update({
  id: '/playground/nft/issue',
  path: '/playground/nft/issue',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundNftIssueMultipleRoute =
  DocsPlaygroundNftIssueMultipleRouteImport.update({
    id: '/playground/nft/issue-multiple',
    path: '/playground/nft/issue-multiple',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPlaygroundNftTransferRoute =
  DocsPlaygroundNftTransferRouteImport.update({
    id: '/playground/nft/transfer',
    path: '/playground/nft/transfer',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPlaygroundPaymentsEngineRoute =
  DocsPlaygroundPaymentsEngineRouteImport.update({
    id: '/playground/payments/engine',
    path: '/playground/payments/engine',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPlaygroundPaymentsNativeRoute =
  DocsPlaygroundPaymentsNativeRouteImport.update({
    id: '/playground/payments/native',
    path: '/playground/payments/native',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPlaygroundTokenBurnRoute = DocsPlaygroundTokenBurnRouteImport.update({
  id: '/playground/token/burn',
  path: '/playground/token/burn',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundTokenCreateRoute =
  DocsPlaygroundTokenCreateRouteImport.update({
    id: '/playground/token/create',
    path: '/playground/token/create',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPlaygroundTokenIssueRoute =
  DocsPlaygroundTokenIssueRouteImport.update({
    id: '/playground/token/issue',
    path: '/playground/token/issue',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsPlaygroundTokenTransferRoute =
  DocsPlaygroundTokenTransferRouteImport.update({
    id: '/playground/token/transfer',
    path: '/playground/token/transfer',
    getParentRoute: () => DocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/account-aliases': typeof DocsAccountAliasesRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/backend': typeof DocsBackendRoute
  '/docs/block-stream': typeof DocsBlockStreamRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/custom-json': typeof DocsCustomJsonRoute
  '/docs/custom-json-parser': typeof DocsCustomJsonParserRoute
  '/docs/engine-payments': typeof DocsEnginePaymentsRoute
  '/docs/environment-variables': typeof DocsEnvironmentVariablesRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/hive-engine': typeof DocsHiveEngineRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/keychain': typeof DocsKeychainRoute
  '/docs/native-payments': typeof DocsNativePaymentsRoute
  '/docs/nft-issuer': typeof DocsNftIssuerRoute
  '/docs/payment-stream': typeof DocsPaymentStreamRoute
  '/docs/payment-validation': typeof DocsPaymentValidationRoute
  '/docs/payments': typeof DocsPaymentsRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/raw-custom-json': typeof DocsRawCustomJsonRoute
  '/docs/raw-rpc': typeof DocsRawRpcRoute
  '/docs/release-notes': typeof DocsReleaseNotesRoute
  '/docs/rpc-resolution': typeof DocsRpcResolutionRoute
  '/docs/token-issuer': typeof DocsTokenIssuerRoute
  '/docs/transaction-reader': typeof DocsTransactionReaderRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/types': typeof DocsTypesRoute
  '/docs/unified-stream': typeof DocsUnifiedStreamRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/nfts/burn': typeof DocsNftsBurnRoute
  '/docs/nfts/create': typeof DocsNftsCreateRoute
  '/docs/nfts/issue': typeof DocsNftsIssueRoute
  '/docs/nfts/issue-multiple': typeof DocsNftsIssueMultipleRoute
  '/docs/nfts/transfer': typeof DocsNftsTransferRoute
  '/docs/playground/configurations': typeof DocsPlaygroundConfigurationsRoute
  '/docs/playground/custom-json': typeof DocsPlaygroundCustomJsonRoute
  '/docs/playground/keychain': typeof DocsPlaygroundKeychainRoute
  '/docs/playground/nodes': typeof DocsPlaygroundNodesRoute
  '/docs/playground/payment-monitor': typeof DocsPlaygroundPaymentMonitorRoute
  '/docs/playground/raw-custom-json': typeof DocsPlaygroundRawCustomJsonRoute
  '/docs/playground/reader': typeof DocsPlaygroundReaderRoute
  '/docs/playground/rpc': typeof DocsPlaygroundRpcRoute
  '/docs/playground/unified-stream': typeof DocsPlaygroundUnifiedStreamRoute
  '/docs/tokens/burn': typeof DocsTokensBurnRoute
  '/docs/tokens/create': typeof DocsTokensCreateRoute
  '/docs/tokens/issue': typeof DocsTokensIssueRoute
  '/docs/tokens/transfer': typeof DocsTokensTransferRoute
  '/docs/playground/': typeof DocsPlaygroundIndexRoute
  '/docs/playground/nft/burn': typeof DocsPlaygroundNftBurnRoute
  '/docs/playground/nft/create': typeof DocsPlaygroundNftCreateRoute
  '/docs/playground/nft/issue': typeof DocsPlaygroundNftIssueRoute
  '/docs/playground/nft/issue-multiple': typeof DocsPlaygroundNftIssueMultipleRoute
  '/docs/playground/nft/transfer': typeof DocsPlaygroundNftTransferRoute
  '/docs/playground/payments/engine': typeof DocsPlaygroundPaymentsEngineRoute
  '/docs/playground/payments/native': typeof DocsPlaygroundPaymentsNativeRoute
  '/docs/playground/token/burn': typeof DocsPlaygroundTokenBurnRoute
  '/docs/playground/token/create': typeof DocsPlaygroundTokenCreateRoute
  '/docs/playground/token/issue': typeof DocsPlaygroundTokenIssueRoute
  '/docs/playground/token/transfer': typeof DocsPlaygroundTokenTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/account-aliases': typeof DocsAccountAliasesRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/backend': typeof DocsBackendRoute
  '/docs/block-stream': typeof DocsBlockStreamRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/custom-json': typeof DocsCustomJsonRoute
  '/docs/custom-json-parser': typeof DocsCustomJsonParserRoute
  '/docs/engine-payments': typeof DocsEnginePaymentsRoute
  '/docs/environment-variables': typeof DocsEnvironmentVariablesRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/hive-engine': typeof DocsHiveEngineRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/keychain': typeof DocsKeychainRoute
  '/docs/native-payments': typeof DocsNativePaymentsRoute
  '/docs/nft-issuer': typeof DocsNftIssuerRoute
  '/docs/payment-stream': typeof DocsPaymentStreamRoute
  '/docs/payment-validation': typeof DocsPaymentValidationRoute
  '/docs/payments': typeof DocsPaymentsRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/raw-custom-json': typeof DocsRawCustomJsonRoute
  '/docs/raw-rpc': typeof DocsRawRpcRoute
  '/docs/release-notes': typeof DocsReleaseNotesRoute
  '/docs/rpc-resolution': typeof DocsRpcResolutionRoute
  '/docs/token-issuer': typeof DocsTokenIssuerRoute
  '/docs/transaction-reader': typeof DocsTransactionReaderRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/types': typeof DocsTypesRoute
  '/docs/unified-stream': typeof DocsUnifiedStreamRoute
  '/docs': typeof DocsIndexRoute
  '/docs/nfts/burn': typeof DocsNftsBurnRoute
  '/docs/nfts/create': typeof DocsNftsCreateRoute
  '/docs/nfts/issue': typeof DocsNftsIssueRoute
  '/docs/nfts/issue-multiple': typeof DocsNftsIssueMultipleRoute
  '/docs/nfts/transfer': typeof DocsNftsTransferRoute
  '/docs/playground/configurations': typeof DocsPlaygroundConfigurationsRoute
  '/docs/playground/custom-json': typeof DocsPlaygroundCustomJsonRoute
  '/docs/playground/keychain': typeof DocsPlaygroundKeychainRoute
  '/docs/playground/nodes': typeof DocsPlaygroundNodesRoute
  '/docs/playground/payment-monitor': typeof DocsPlaygroundPaymentMonitorRoute
  '/docs/playground/raw-custom-json': typeof DocsPlaygroundRawCustomJsonRoute
  '/docs/playground/reader': typeof DocsPlaygroundReaderRoute
  '/docs/playground/rpc': typeof DocsPlaygroundRpcRoute
  '/docs/playground/unified-stream': typeof DocsPlaygroundUnifiedStreamRoute
  '/docs/tokens/burn': typeof DocsTokensBurnRoute
  '/docs/tokens/create': typeof DocsTokensCreateRoute
  '/docs/tokens/issue': typeof DocsTokensIssueRoute
  '/docs/tokens/transfer': typeof DocsTokensTransferRoute
  '/docs/playground': typeof DocsPlaygroundIndexRoute
  '/docs/playground/nft/burn': typeof DocsPlaygroundNftBurnRoute
  '/docs/playground/nft/create': typeof DocsPlaygroundNftCreateRoute
  '/docs/playground/nft/issue': typeof DocsPlaygroundNftIssueRoute
  '/docs/playground/nft/issue-multiple': typeof DocsPlaygroundNftIssueMultipleRoute
  '/docs/playground/nft/transfer': typeof DocsPlaygroundNftTransferRoute
  '/docs/playground/payments/engine': typeof DocsPlaygroundPaymentsEngineRoute
  '/docs/playground/payments/native': typeof DocsPlaygroundPaymentsNativeRoute
  '/docs/playground/token/burn': typeof DocsPlaygroundTokenBurnRoute
  '/docs/playground/token/create': typeof DocsPlaygroundTokenCreateRoute
  '/docs/playground/token/issue': typeof DocsPlaygroundTokenIssueRoute
  '/docs/playground/token/transfer': typeof DocsPlaygroundTokenTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/account-aliases': typeof DocsAccountAliasesRoute
  '/docs/api-reference': typeof DocsApiReferenceRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/backend': typeof DocsBackendRoute
  '/docs/block-stream': typeof DocsBlockStreamRoute
  '/docs/compatibility': typeof DocsCompatibilityRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/custom-json': typeof DocsCustomJsonRoute
  '/docs/custom-json-parser': typeof DocsCustomJsonParserRoute
  '/docs/engine-payments': typeof DocsEnginePaymentsRoute
  '/docs/environment-variables': typeof DocsEnvironmentVariablesRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/hive-engine': typeof DocsHiveEngineRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/keychain': typeof DocsKeychainRoute
  '/docs/native-payments': typeof DocsNativePaymentsRoute
  '/docs/nft-issuer': typeof DocsNftIssuerRoute
  '/docs/payment-stream': typeof DocsPaymentStreamRoute
  '/docs/payment-validation': typeof DocsPaymentValidationRoute
  '/docs/payments': typeof DocsPaymentsRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/raw-custom-json': typeof DocsRawCustomJsonRoute
  '/docs/raw-rpc': typeof DocsRawRpcRoute
  '/docs/release-notes': typeof DocsReleaseNotesRoute
  '/docs/rpc-resolution': typeof DocsRpcResolutionRoute
  '/docs/token-issuer': typeof DocsTokenIssuerRoute
  '/docs/transaction-reader': typeof DocsTransactionReaderRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/types': typeof DocsTypesRoute
  '/docs/unified-stream': typeof DocsUnifiedStreamRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/nfts/burn': typeof DocsNftsBurnRoute
  '/docs/nfts/create': typeof DocsNftsCreateRoute
  '/docs/nfts/issue': typeof DocsNftsIssueRoute
  '/docs/nfts/issue-multiple': typeof DocsNftsIssueMultipleRoute
  '/docs/nfts/transfer': typeof DocsNftsTransferRoute
  '/docs/playground/configurations': typeof DocsPlaygroundConfigurationsRoute
  '/docs/playground/custom-json': typeof DocsPlaygroundCustomJsonRoute
  '/docs/playground/keychain': typeof DocsPlaygroundKeychainRoute
  '/docs/playground/nodes': typeof DocsPlaygroundNodesRoute
  '/docs/playground/payment-monitor': typeof DocsPlaygroundPaymentMonitorRoute
  '/docs/playground/raw-custom-json': typeof DocsPlaygroundRawCustomJsonRoute
  '/docs/playground/reader': typeof DocsPlaygroundReaderRoute
  '/docs/playground/rpc': typeof DocsPlaygroundRpcRoute
  '/docs/playground/unified-stream': typeof DocsPlaygroundUnifiedStreamRoute
  '/docs/tokens/burn': typeof DocsTokensBurnRoute
  '/docs/tokens/create': typeof DocsTokensCreateRoute
  '/docs/tokens/issue': typeof DocsTokensIssueRoute
  '/docs/tokens/transfer': typeof DocsTokensTransferRoute
  '/docs/playground/': typeof DocsPlaygroundIndexRoute
  '/docs/playground/nft/burn': typeof DocsPlaygroundNftBurnRoute
  '/docs/playground/nft/create': typeof DocsPlaygroundNftCreateRoute
  '/docs/playground/nft/issue': typeof DocsPlaygroundNftIssueRoute
  '/docs/playground/nft/issue-multiple': typeof DocsPlaygroundNftIssueMultipleRoute
  '/docs/playground/nft/transfer': typeof DocsPlaygroundNftTransferRoute
  '/docs/playground/payments/engine': typeof DocsPlaygroundPaymentsEngineRoute
  '/docs/playground/payments/native': typeof DocsPlaygroundPaymentsNativeRoute
  '/docs/playground/token/burn': typeof DocsPlaygroundTokenBurnRoute
  '/docs/playground/token/create': typeof DocsPlaygroundTokenCreateRoute
  '/docs/playground/token/issue': typeof DocsPlaygroundTokenIssueRoute
  '/docs/playground/token/transfer': typeof DocsPlaygroundTokenTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/account-aliases'
    | '/docs/api-reference'
    | '/docs/architecture'
    | '/docs/backend'
    | '/docs/block-stream'
    | '/docs/compatibility'
    | '/docs/configuration'
    | '/docs/custom-json'
    | '/docs/custom-json-parser'
    | '/docs/engine-payments'
    | '/docs/environment-variables'
    | '/docs/errors'
    | '/docs/hive-engine'
    | '/docs/installation'
    | '/docs/keychain'
    | '/docs/native-payments'
    | '/docs/nft-issuer'
    | '/docs/payment-stream'
    | '/docs/payment-validation'
    | '/docs/payments'
    | '/docs/quick-start'
    | '/docs/raw-custom-json'
    | '/docs/raw-rpc'
    | '/docs/release-notes'
    | '/docs/rpc-resolution'
    | '/docs/token-issuer'
    | '/docs/transaction-reader'
    | '/docs/troubleshooting'
    | '/docs/types'
    | '/docs/unified-stream'
    | '/docs/'
    | '/docs/nfts/burn'
    | '/docs/nfts/create'
    | '/docs/nfts/issue'
    | '/docs/nfts/issue-multiple'
    | '/docs/nfts/transfer'
    | '/docs/playground/configurations'
    | '/docs/playground/custom-json'
    | '/docs/playground/keychain'
    | '/docs/playground/nodes'
    | '/docs/playground/payment-monitor'
    | '/docs/playground/raw-custom-json'
    | '/docs/playground/reader'
    | '/docs/playground/rpc'
    | '/docs/playground/unified-stream'
    | '/docs/tokens/burn'
    | '/docs/tokens/create'
    | '/docs/tokens/issue'
    | '/docs/tokens/transfer'
    | '/docs/playground/'
    | '/docs/playground/nft/burn'
    | '/docs/playground/nft/create'
    | '/docs/playground/nft/issue'
    | '/docs/playground/nft/issue-multiple'
    | '/docs/playground/nft/transfer'
    | '/docs/playground/payments/engine'
    | '/docs/playground/payments/native'
    | '/docs/playground/token/burn'
    | '/docs/playground/token/create'
    | '/docs/playground/token/issue'
    | '/docs/playground/token/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/account-aliases'
    | '/docs/api-reference'
    | '/docs/architecture'
    | '/docs/backend'
    | '/docs/block-stream'
    | '/docs/compatibility'
    | '/docs/configuration'
    | '/docs/custom-json'
    | '/docs/custom-json-parser'
    | '/docs/engine-payments'
    | '/docs/environment-variables'
    | '/docs/errors'
    | '/docs/hive-engine'
    | '/docs/installation'
    | '/docs/keychain'
    | '/docs/native-payments'
    | '/docs/nft-issuer'
    | '/docs/payment-stream'
    | '/docs/payment-validation'
    | '/docs/payments'
    | '/docs/quick-start'
    | '/docs/raw-custom-json'
    | '/docs/raw-rpc'
    | '/docs/release-notes'
    | '/docs/rpc-resolution'
    | '/docs/token-issuer'
    | '/docs/transaction-reader'
    | '/docs/troubleshooting'
    | '/docs/types'
    | '/docs/unified-stream'
    | '/docs'
    | '/docs/nfts/burn'
    | '/docs/nfts/create'
    | '/docs/nfts/issue'
    | '/docs/nfts/issue-multiple'
    | '/docs/nfts/transfer'
    | '/docs/playground/configurations'
    | '/docs/playground/custom-json'
    | '/docs/playground/keychain'
    | '/docs/playground/nodes'
    | '/docs/playground/payment-monitor'
    | '/docs/playground/raw-custom-json'
    | '/docs/playground/reader'
    | '/docs/playground/rpc'
    | '/docs/playground/unified-stream'
    | '/docs/tokens/burn'
    | '/docs/tokens/create'
    | '/docs/tokens/issue'
    | '/docs/tokens/transfer'
    | '/docs/playground'
    | '/docs/playground/nft/burn'
    | '/docs/playground/nft/create'
    | '/docs/playground/nft/issue'
    | '/docs/playground/nft/issue-multiple'
    | '/docs/playground/nft/transfer'
    | '/docs/playground/payments/engine'
    | '/docs/playground/payments/native'
    | '/docs/playground/token/burn'
    | '/docs/playground/token/create'
    | '/docs/playground/token/issue'
    | '/docs/playground/token/transfer'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/account-aliases'
    | '/docs/api-reference'
    | '/docs/architecture'
    | '/docs/backend'
    | '/docs/block-stream'
    | '/docs/compatibility'
    | '/docs/configuration'
    | '/docs/custom-json'
    | '/docs/custom-json-parser'
    | '/docs/engine-payments'
    | '/docs/environment-variables'
    | '/docs/errors'
    | '/docs/hive-engine'
    | '/docs/installation'
    | '/docs/keychain'
    | '/docs/native-payments'
    | '/docs/nft-issuer'
    | '/docs/payment-stream'
    | '/docs/payment-validation'
    | '/docs/payments'
    | '/docs/quick-start'
    | '/docs/raw-custom-json'
    | '/docs/raw-rpc'
    | '/docs/release-notes'
    | '/docs/rpc-resolution'
    | '/docs/token-issuer'
    | '/docs/transaction-reader'
    | '/docs/troubleshooting'
    | '/docs/types'
    | '/docs/unified-stream'
    | '/docs/'
    | '/docs/nfts/burn'
    | '/docs/nfts/create'
    | '/docs/nfts/issue'
    | '/docs/nfts/issue-multiple'
    | '/docs/nfts/transfer'
    | '/docs/playground/configurations'
    | '/docs/playground/custom-json'
    | '/docs/playground/keychain'
    | '/docs/playground/nodes'
    | '/docs/playground/payment-monitor'
    | '/docs/playground/raw-custom-json'
    | '/docs/playground/reader'
    | '/docs/playground/rpc'
    | '/docs/playground/unified-stream'
    | '/docs/tokens/burn'
    | '/docs/tokens/create'
    | '/docs/tokens/issue'
    | '/docs/tokens/transfer'
    | '/docs/playground/'
    | '/docs/playground/nft/burn'
    | '/docs/playground/nft/create'
    | '/docs/playground/nft/issue'
    | '/docs/playground/nft/issue-multiple'
    | '/docs/playground/nft/transfer'
    | '/docs/playground/payments/engine'
    | '/docs/playground/payments/native'
    | '/docs/playground/token/burn'
    | '/docs/playground/token/create'
    | '/docs/playground/token/issue'
    | '/docs/playground/token/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/account-aliases': {
      id: '/docs/account-aliases'
      path: '/account-aliases'
      fullPath: '/docs/account-aliases'
      preLoaderRoute: typeof DocsAccountAliasesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api-reference': {
      id: '/docs/api-reference'
      path: '/api-reference'
      fullPath: '/docs/api-reference'
      preLoaderRoute: typeof DocsApiReferenceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/backend': {
      id: '/docs/backend'
      path: '/backend'
      fullPath: '/docs/backend'
      preLoaderRoute: typeof DocsBackendRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/block-stream': {
      id: '/docs/block-stream'
      path: '/block-stream'
      fullPath: '/docs/block-stream'
      preLoaderRoute: typeof DocsBlockStreamRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/compatibility': {
      id: '/docs/compatibility'
      path: '/compatibility'
      fullPath: '/docs/compatibility'
      preLoaderRoute: typeof DocsCompatibilityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/custom-json': {
      id: '/docs/custom-json'
      path: '/custom-json'
      fullPath: '/docs/custom-json'
      preLoaderRoute: typeof DocsCustomJsonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/custom-json-parser': {
      id: '/docs/custom-json-parser'
      path: '/custom-json-parser'
      fullPath: '/docs/custom-json-parser'
      preLoaderRoute: typeof DocsCustomJsonParserRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/engine-payments': {
      id: '/docs/engine-payments'
      path: '/engine-payments'
      fullPath: '/docs/engine-payments'
      preLoaderRoute: typeof DocsEnginePaymentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/environment-variables': {
      id: '/docs/environment-variables'
      path: '/environment-variables'
      fullPath: '/docs/environment-variables'
      preLoaderRoute: typeof DocsEnvironmentVariablesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/errors': {
      id: '/docs/errors'
      path: '/errors'
      fullPath: '/docs/errors'
      preLoaderRoute: typeof DocsErrorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/hive-engine': {
      id: '/docs/hive-engine'
      path: '/hive-engine'
      fullPath: '/docs/hive-engine'
      preLoaderRoute: typeof DocsHiveEngineRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/keychain': {
      id: '/docs/keychain'
      path: '/keychain'
      fullPath: '/docs/keychain'
      preLoaderRoute: typeof DocsKeychainRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/native-payments': {
      id: '/docs/native-payments'
      path: '/native-payments'
      fullPath: '/docs/native-payments'
      preLoaderRoute: typeof DocsNativePaymentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nft-issuer': {
      id: '/docs/nft-issuer'
      path: '/nft-issuer'
      fullPath: '/docs/nft-issuer'
      preLoaderRoute: typeof DocsNftIssuerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/payment-stream': {
      id: '/docs/payment-stream'
      path: '/payment-stream'
      fullPath: '/docs/payment-stream'
      preLoaderRoute: typeof DocsPaymentStreamRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/payment-validation': {
      id: '/docs/payment-validation'
      path: '/payment-validation'
      fullPath: '/docs/payment-validation'
      preLoaderRoute: typeof DocsPaymentValidationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/payments': {
      id: '/docs/payments'
      path: '/payments'
      fullPath: '/docs/payments'
      preLoaderRoute: typeof DocsPaymentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quick-start': {
      id: '/docs/quick-start'
      path: '/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/raw-custom-json': {
      id: '/docs/raw-custom-json'
      path: '/raw-custom-json'
      fullPath: '/docs/raw-custom-json'
      preLoaderRoute: typeof DocsRawCustomJsonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/raw-rpc': {
      id: '/docs/raw-rpc'
      path: '/raw-rpc'
      fullPath: '/docs/raw-rpc'
      preLoaderRoute: typeof DocsRawRpcRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/release-notes': {
      id: '/docs/release-notes'
      path: '/release-notes'
      fullPath: '/docs/release-notes'
      preLoaderRoute: typeof DocsReleaseNotesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/rpc-resolution': {
      id: '/docs/rpc-resolution'
      path: '/rpc-resolution'
      fullPath: '/docs/rpc-resolution'
      preLoaderRoute: typeof DocsRpcResolutionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/token-issuer': {
      id: '/docs/token-issuer'
      path: '/token-issuer'
      fullPath: '/docs/token-issuer'
      preLoaderRoute: typeof DocsTokenIssuerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/transaction-reader': {
      id: '/docs/transaction-reader'
      path: '/transaction-reader'
      fullPath: '/docs/transaction-reader'
      preLoaderRoute: typeof DocsTransactionReaderRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/types': {
      id: '/docs/types'
      path: '/types'
      fullPath: '/docs/types'
      preLoaderRoute: typeof DocsTypesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/unified-stream': {
      id: '/docs/unified-stream'
      path: '/unified-stream'
      fullPath: '/docs/unified-stream'
      preLoaderRoute: typeof DocsUnifiedStreamRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nfts/burn': {
      id: '/docs/nfts/burn'
      path: '/nfts/burn'
      fullPath: '/docs/nfts/burn'
      preLoaderRoute: typeof DocsNftsBurnRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nfts/create': {
      id: '/docs/nfts/create'
      path: '/nfts/create'
      fullPath: '/docs/nfts/create'
      preLoaderRoute: typeof DocsNftsCreateRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nfts/issue': {
      id: '/docs/nfts/issue'
      path: '/nfts/issue'
      fullPath: '/docs/nfts/issue'
      preLoaderRoute: typeof DocsNftsIssueRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nfts/issue-multiple': {
      id: '/docs/nfts/issue-multiple'
      path: '/nfts/issue-multiple'
      fullPath: '/docs/nfts/issue-multiple'
      preLoaderRoute: typeof DocsNftsIssueMultipleRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/nfts/transfer': {
      id: '/docs/nfts/transfer'
      path: '/nfts/transfer'
      fullPath: '/docs/nfts/transfer'
      preLoaderRoute: typeof DocsNftsTransferRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/': {
      id: '/docs/playground/'
      path: '/playground'
      fullPath: '/docs/playground/'
      preLoaderRoute: typeof DocsPlaygroundIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/configurations': {
      id: '/docs/playground/configurations'
      path: '/playground/configurations'
      fullPath: '/docs/playground/configurations'
      preLoaderRoute: typeof DocsPlaygroundConfigurationsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/custom-json': {
      id: '/docs/playground/custom-json'
      path: '/playground/custom-json'
      fullPath: '/docs/playground/custom-json'
      preLoaderRoute: typeof DocsPlaygroundCustomJsonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/keychain': {
      id: '/docs/playground/keychain'
      path: '/playground/keychain'
      fullPath: '/docs/playground/keychain'
      preLoaderRoute: typeof DocsPlaygroundKeychainRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/nodes': {
      id: '/docs/playground/nodes'
      path: '/playground/nodes'
      fullPath: '/docs/playground/nodes'
      preLoaderRoute: typeof DocsPlaygroundNodesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/payment-monitor': {
      id: '/docs/playground/payment-monitor'
      path: '/playground/payment-monitor'
      fullPath: '/docs/playground/payment-monitor'
      preLoaderRoute: typeof DocsPlaygroundPaymentMonitorRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/raw-custom-json': {
      id: '/docs/playground/raw-custom-json'
      path: '/playground/raw-custom-json'
      fullPath: '/docs/playground/raw-custom-json'
      preLoaderRoute: typeof DocsPlaygroundRawCustomJsonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/reader': {
      id: '/docs/playground/reader'
      path: '/playground/reader'
      fullPath: '/docs/playground/reader'
      preLoaderRoute: typeof DocsPlaygroundReaderRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/rpc': {
      id: '/docs/playground/rpc'
      path: '/playground/rpc'
      fullPath: '/docs/playground/rpc'
      preLoaderRoute: typeof DocsPlaygroundRpcRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/unified-stream': {
      id: '/docs/playground/unified-stream'
      path: '/playground/unified-stream'
      fullPath: '/docs/playground/unified-stream'
      preLoaderRoute: typeof DocsPlaygroundUnifiedStreamRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tokens/burn': {
      id: '/docs/tokens/burn'
      path: '/tokens/burn'
      fullPath: '/docs/tokens/burn'
      preLoaderRoute: typeof DocsTokensBurnRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tokens/create': {
      id: '/docs/tokens/create'
      path: '/tokens/create'
      fullPath: '/docs/tokens/create'
      preLoaderRoute: typeof DocsTokensCreateRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tokens/issue': {
      id: '/docs/tokens/issue'
      path: '/tokens/issue'
      fullPath: '/docs/tokens/issue'
      preLoaderRoute: typeof DocsTokensIssueRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tokens/transfer': {
      id: '/docs/tokens/transfer'
      path: '/tokens/transfer'
      fullPath: '/docs/tokens/transfer'
      preLoaderRoute: typeof DocsTokensTransferRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/nft/burn': {
      id: '/docs/playground/nft/burn'
      path: '/playground/nft/burn'
      fullPath: '/docs/playground/nft/burn'
      preLoaderRoute: typeof DocsPlaygroundNftBurnRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/nft/create': {
      id: '/docs/playground/nft/create'
      path: '/playground/nft/create'
      fullPath: '/docs/playground/nft/create'
      preLoaderRoute: typeof DocsPlaygroundNftCreateRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/nft/issue': {
      id: '/docs/playground/nft/issue'
      path: '/playground/nft/issue'
      fullPath: '/docs/playground/nft/issue'
      preLoaderRoute: typeof DocsPlaygroundNftIssueRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/nft/issue-multiple': {
      id: '/docs/playground/nft/issue-multiple'
      path: '/playground/nft/issue-multiple'
      fullPath: '/docs/playground/nft/issue-multiple'
      preLoaderRoute: typeof DocsPlaygroundNftIssueMultipleRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/nft/transfer': {
      id: '/docs/playground/nft/transfer'
      path: '/playground/nft/transfer'
      fullPath: '/docs/playground/nft/transfer'
      preLoaderRoute: typeof DocsPlaygroundNftTransferRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/payments/engine': {
      id: '/docs/playground/payments/engine'
      path: '/playground/payments/engine'
      fullPath: '/docs/playground/payments/engine'
      preLoaderRoute: typeof DocsPlaygroundPaymentsEngineRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/payments/native': {
      id: '/docs/playground/payments/native'
      path: '/playground/payments/native'
      fullPath: '/docs/playground/payments/native'
      preLoaderRoute: typeof DocsPlaygroundPaymentsNativeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/token/burn': {
      id: '/docs/playground/token/burn'
      path: '/playground/token/burn'
      fullPath: '/docs/playground/token/burn'
      preLoaderRoute: typeof DocsPlaygroundTokenBurnRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/token/create': {
      id: '/docs/playground/token/create'
      path: '/playground/token/create'
      fullPath: '/docs/playground/token/create'
      preLoaderRoute: typeof DocsPlaygroundTokenCreateRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/token/issue': {
      id: '/docs/playground/token/issue'
      path: '/playground/token/issue'
      fullPath: '/docs/playground/token/issue'
      preLoaderRoute: typeof DocsPlaygroundTokenIssueRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground/token/transfer': {
      id: '/docs/playground/token/transfer'
      path: '/playground/token/transfer'
      fullPath: '/docs/playground/token/transfer'
      preLoaderRoute: typeof DocsPlaygroundTokenTransferRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsAccountAliasesRoute: typeof DocsAccountAliasesRoute
  DocsApiReferenceRoute: typeof DocsApiReferenceRoute
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsBackendRoute: typeof DocsBackendRoute
  DocsBlockStreamRoute: typeof DocsBlockStreamRoute
  DocsCompatibilityRoute: typeof DocsCompatibilityRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsCustomJsonRoute: typeof DocsCustomJsonRoute
  DocsCustomJsonParserRoute: typeof DocsCustomJsonParserRoute
  DocsEnginePaymentsRoute: typeof DocsEnginePaymentsRoute
  DocsEnvironmentVariablesRoute: typeof DocsEnvironmentVariablesRoute
  DocsErrorsRoute: typeof DocsErrorsRoute
  DocsHiveEngineRoute: typeof DocsHiveEngineRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsKeychainRoute: typeof DocsKeychainRoute
  DocsNativePaymentsRoute: typeof DocsNativePaymentsRoute
  DocsNftIssuerRoute: typeof DocsNftIssuerRoute
  DocsPaymentStreamRoute: typeof DocsPaymentStreamRoute
  DocsPaymentValidationRoute: typeof DocsPaymentValidationRoute
  DocsPaymentsRoute: typeof DocsPaymentsRoute
  DocsQuickStartRoute: typeof DocsQuickStartRoute
  DocsRawCustomJsonRoute: typeof DocsRawCustomJsonRoute
  DocsRawRpcRoute: typeof DocsRawRpcRoute
  DocsReleaseNotesRoute: typeof DocsReleaseNotesRoute
  DocsRpcResolutionRoute: typeof DocsRpcResolutionRoute
  DocsTokenIssuerRoute: typeof DocsTokenIssuerRoute
  DocsTransactionReaderRoute: typeof DocsTransactionReaderRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsTypesRoute: typeof DocsTypesRoute
  DocsUnifiedStreamRoute: typeof DocsUnifiedStreamRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsNftsBurnRoute: typeof DocsNftsBurnRoute
  DocsNftsCreateRoute: typeof DocsNftsCreateRoute
  DocsNftsIssueRoute: typeof DocsNftsIssueRoute
  DocsNftsIssueMultipleRoute: typeof DocsNftsIssueMultipleRoute
  DocsNftsTransferRoute: typeof DocsNftsTransferRoute
  DocsPlaygroundConfigurationsRoute: typeof DocsPlaygroundConfigurationsRoute
  DocsPlaygroundCustomJsonRoute: typeof DocsPlaygroundCustomJsonRoute
  DocsPlaygroundKeychainRoute: typeof DocsPlaygroundKeychainRoute
  DocsPlaygroundNodesRoute: typeof DocsPlaygroundNodesRoute
  DocsPlaygroundPaymentMonitorRoute: typeof DocsPlaygroundPaymentMonitorRoute
  DocsPlaygroundRawCustomJsonRoute: typeof DocsPlaygroundRawCustomJsonRoute
  DocsPlaygroundReaderRoute: typeof DocsPlaygroundReaderRoute
  DocsPlaygroundRpcRoute: typeof DocsPlaygroundRpcRoute
  DocsPlaygroundUnifiedStreamRoute: typeof DocsPlaygroundUnifiedStreamRoute
  DocsTokensBurnRoute: typeof DocsTokensBurnRoute
  DocsTokensCreateRoute: typeof DocsTokensCreateRoute
  DocsTokensIssueRoute: typeof DocsTokensIssueRoute
  DocsTokensTransferRoute: typeof DocsTokensTransferRoute
  DocsPlaygroundIndexRoute: typeof DocsPlaygroundIndexRoute
  DocsPlaygroundNftBurnRoute: typeof DocsPlaygroundNftBurnRoute
  DocsPlaygroundNftCreateRoute: typeof DocsPlaygroundNftCreateRoute
  DocsPlaygroundNftIssueRoute: typeof DocsPlaygroundNftIssueRoute
  DocsPlaygroundNftIssueMultipleRoute: typeof DocsPlaygroundNftIssueMultipleRoute
  DocsPlaygroundNftTransferRoute: typeof DocsPlaygroundNftTransferRoute
  DocsPlaygroundPaymentsEngineRoute: typeof DocsPlaygroundPaymentsEngineRoute
  DocsPlaygroundPaymentsNativeRoute: typeof DocsPlaygroundPaymentsNativeRoute
  DocsPlaygroundTokenBurnRoute: typeof DocsPlaygroundTokenBurnRoute
  DocsPlaygroundTokenCreateRoute: typeof DocsPlaygroundTokenCreateRoute
  DocsPlaygroundTokenIssueRoute: typeof DocsPlaygroundTokenIssueRoute
  DocsPlaygroundTokenTransferRoute: typeof DocsPlaygroundTokenTransferRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAccountAliasesRoute: DocsAccountAliasesRoute,
  DocsApiReferenceRoute: DocsApiReferenceRoute,
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsBackendRoute: DocsBackendRoute,
  DocsBlockStreamRoute: DocsBlockStreamRoute,
  DocsCompatibilityRoute: DocsCompatibilityRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsCustomJsonRoute: DocsCustomJsonRoute,
  DocsCustomJsonParserRoute: DocsCustomJsonParserRoute,
  DocsEnginePaymentsRoute: DocsEnginePaymentsRoute,
  DocsEnvironmentVariablesRoute: DocsEnvironmentVariablesRoute,
  DocsErrorsRoute: DocsErrorsRoute,
  DocsHiveEngineRoute: DocsHiveEngineRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsKeychainRoute: DocsKeychainRoute,
  DocsNativePaymentsRoute: DocsNativePaymentsRoute,
  DocsNftIssuerRoute: DocsNftIssuerRoute,
  DocsPaymentStreamRoute: DocsPaymentStreamRoute,
  DocsPaymentValidationRoute: DocsPaymentValidationRoute,
  DocsPaymentsRoute: DocsPaymentsRoute,
  DocsQuickStartRoute: DocsQuickStartRoute,
  DocsRawCustomJsonRoute: DocsRawCustomJsonRoute,
  DocsRawRpcRoute: DocsRawRpcRoute,
  DocsReleaseNotesRoute: DocsReleaseNotesRoute,
  DocsRpcResolutionRoute: DocsRpcResolutionRoute,
  DocsTokenIssuerRoute: DocsTokenIssuerRoute,
  DocsTransactionReaderRoute: DocsTransactionReaderRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsTypesRoute: DocsTypesRoute,
  DocsUnifiedStreamRoute: DocsUnifiedStreamRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsNftsBurnRoute: DocsNftsBurnRoute,
  DocsNftsCreateRoute: DocsNftsCreateRoute,
  DocsNftsIssueRoute: DocsNftsIssueRoute,
  DocsNftsIssueMultipleRoute: DocsNftsIssueMultipleRoute,
  DocsNftsTransferRoute: DocsNftsTransferRoute,
  DocsPlaygroundConfigurationsRoute: DocsPlaygroundConfigurationsRoute,
  DocsPlaygroundCustomJsonRoute: DocsPlaygroundCustomJsonRoute,
  DocsPlaygroundKeychainRoute: DocsPlaygroundKeychainRoute,
  DocsPlaygroundNodesRoute: DocsPlaygroundNodesRoute,
  DocsPlaygroundPaymentMonitorRoute: DocsPlaygroundPaymentMonitorRoute,
  DocsPlaygroundRawCustomJsonRoute: DocsPlaygroundRawCustomJsonRoute,
  DocsPlaygroundReaderRoute: DocsPlaygroundReaderRoute,
  DocsPlaygroundRpcRoute: DocsPlaygroundRpcRoute,
  DocsPlaygroundUnifiedStreamRoute: DocsPlaygroundUnifiedStreamRoute,
  DocsTokensBurnRoute: DocsTokensBurnRoute,
  DocsTokensCreateRoute: DocsTokensCreateRoute,
  DocsTokensIssueRoute: DocsTokensIssueRoute,
  DocsTokensTransferRoute: DocsTokensTransferRoute,
  DocsPlaygroundIndexRoute: DocsPlaygroundIndexRoute,
  DocsPlaygroundNftBurnRoute: DocsPlaygroundNftBurnRoute,
  DocsPlaygroundNftCreateRoute: DocsPlaygroundNftCreateRoute,
  DocsPlaygroundNftIssueRoute: DocsPlaygroundNftIssueRoute,
  DocsPlaygroundNftIssueMultipleRoute: DocsPlaygroundNftIssueMultipleRoute,
  DocsPlaygroundNftTransferRoute: DocsPlaygroundNftTransferRoute,
  DocsPlaygroundPaymentsEngineRoute: DocsPlaygroundPaymentsEngineRoute,
  DocsPlaygroundPaymentsNativeRoute: DocsPlaygroundPaymentsNativeRoute,
  DocsPlaygroundTokenBurnRoute: DocsPlaygroundTokenBurnRoute,
  DocsPlaygroundTokenCreateRoute: DocsPlaygroundTokenCreateRoute,
  DocsPlaygroundTokenIssueRoute: DocsPlaygroundTokenIssueRoute,
  DocsPlaygroundTokenTransferRoute: DocsPlaygroundTokenTransferRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
